class Calculator:
    """
    A simple calculator implementation.
    Generated by: Gemini 3 Pro (High)
    Design by: Claude Sonnet 4.5 (Thinking)
    """
    
    def add(self, a, b):
        return a + b

    def subtract(self, a, b):
        return a - b

    def multiply(self, a, b):
        return a * b

    def divide(self, a, b):
        if b == 0:
            raise ValueError("Cannot divide by zero")
        return a / b
