from pydantic import BaseModel


class AnalysisRequest(BaseModel):
    modality: str
    query: str | None = None


class Finding(BaseModel):
    description: str
    severity: str  # "normal", "mild", "moderate", "severe"
    location: str | None = None


class AnalysisResponse(BaseModel):
    modality: str
    summary: str
    findings: list[Finding]
    raw_output: str
    disclaimer: str = (
        "This analysis is generated by an AI model and is intended for "
        "research and educational purposes only. It does not constitute "
        "medical advice or diagnosis. Always consult a qualified healthcare "
        "professional for clinical decisions."
    )
