#!/usr/bin/env python3
"""Build inventories/ruflo.json from a checkout of ruvnet/ruflo.

Reads the marketplace manifest and measures each plugin's actual surface area —
commands, agents, skills, hooks, and whether it registers an MCP server. Surface
area is the input to the "context & interference overhead" criterion, so it is
measured rather than guessed.

    git clone --depth 1 https://github.com/ruvnet/ruflo.git /tmp/ruflo
    python3 scripts/build_ruflo_inventory.py /tmp/ruflo

Standard library only.
"""

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "inventories" / "ruflo.json"


def count(directory, pattern="*.md"):
    return len(list(directory.glob(pattern))) if directory.is_dir() else 0


def profile(plugin_dir):
    """Measure what a plugin adds to a session."""
    manifest = plugin_dir / ".claude-plugin" / "plugin.json"
    meta = json.loads(manifest.read_text()) if manifest.exists() else {}

    mcp_path = plugin_dir / ".mcp.json"
    mcp_servers = []
    if mcp_path.exists():
        mcp_servers = sorted(json.loads(mcp_path.read_text()).get("mcpServers", {}))

    hooks_path = plugin_dir / "hooks" / "hooks.json"
    hook_events = []
    if hooks_path.exists():
        hook_events = sorted(json.loads(hooks_path.read_text()).get("hooks", {}))

    return {
        "version": meta.get("version"),
        "commands": count(plugin_dir / "commands"),
        "agents": count(plugin_dir / "agents"),
        "skills": count(plugin_dir / "skills", "*/SKILL.md"),
        "mcp_servers": mcp_servers,
        "hook_events": hook_events,
    }


def categorise(prof):
    """Group by what the plugin costs a session, not by subject matter."""
    if prof["mcp_servers"] and prof["hook_events"]:
        return "mcp-and-hooks"
    if prof["mcp_servers"]:
        return "mcp-server"
    if prof["hook_events"]:
        return "hooks"
    return "prompt-only"


def requires(prof):
    reqs = []
    if prof["mcp_servers"]:
        reqs.append("node + an MCP server process (" + ", ".join(prof["mcp_servers"]) + ")")
    if prof["hook_events"]:
        reqs.append("hooks on " + ", ".join(prof["hook_events"]))
    return reqs


def resolve_head(git_dir):
    """Return the commit the checkout is on, following one symbolic ref."""
    head_file = git_dir / "HEAD"
    if not head_file.exists():
        return None
    head = head_file.read_text().strip()
    if not head.startswith("ref: "):
        return head
    ref = head[5:]
    ref_file = git_dir / ref
    if ref_file.exists():
        return ref_file.read_text().strip()
    packed = git_dir / "packed-refs"
    if packed.exists():
        for line in packed.read_text().splitlines():
            if line.endswith(f" {ref}"):
                return line.split(" ", 1)[0]
    return None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("checkout", type=pathlib.Path, help="path to a ruvnet/ruflo checkout")
    args = ap.parse_args()

    manifest = args.checkout / ".claude-plugin" / "marketplace.json"
    if not manifest.exists():
        sys.exit(f"not a ruflo checkout: {manifest} missing")

    market = json.loads(manifest.read_text())
    head = resolve_head(args.checkout / ".git")

    entries = []
    for entry in market["plugins"]:
        plugin_dir = args.checkout / entry["source"].lstrip("./")
        if not plugin_dir.is_dir():
            print(f"warning: {entry['name']} has no directory at {plugin_dir}", file=sys.stderr)
            continue
        prof = profile(plugin_dir)
        entries.append({
            "id": entry["name"],
            "name": entry["name"],
            "category": categorise(prof),
            "requires": requires(prof),
            "description": entry.get("description", ""),
            "surface": prof,
        })

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps({
        "_comment": (
            "Ruflo marketplace inventory, generated by scripts/build_ruflo_inventory.py. "
            "'surface' is measured from the plugin source; 'category' groups by session "
            "cost (MCP server / hooks / prompt-only), not by subject matter."
        ),
        "marketplace": market.get("name"),
        "source": "https://github.com/ruvnet/ruflo",
        "checkout_head": head,
        "plugins": entries,
    }, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} plugins)")


if __name__ == "__main__":
    main()
